title: SALU
description: CSC 397/595 Lab Assignment 1

baseurl: "/csc-397-595-lab1"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown

just_the_docs:
  color_scheme: light
  search_enabled: true